name: check with github action

on:
  push:
    branches:
      - "main"

jobs:
  cek-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil kode dari repository (Checkout)
      uses: actions/checkout@v5

    - name: Jalankan Hadolint (Lint Dockerfile)
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./backend/Dockerfile
        failure-threshold: error

    - name: coba build image
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        PORT_APP: ${{ secrets.PORT_APP }}
        PORT_HOST: ${{ secrets.PORT_HOST }}
      run: docker compose -f ./backend/docker-compose.yml up --build -d
